export const quotesArray = [
'I was referred to take the ProBar product management training by a senior Pm and it was absolutely worth it. Being exposed to practical product building was the climax for me.',
 'Through PROBAR, I became more confident as a Product manager and yes, it also gave me my first full time role!',
 'PROBAR is a community of individuals with great dreams, desires to do more for themselves and the Tech space. I have always loved challenges, to acquire more knowledge, learn more about Tech and then opportunity called PROBAR came which i am glad i took. The community is grounded with tutors that knows their onions and crave for more growth for themselves and every scholar in the community. It doesnt just end with the trainings, they groom you, redeisgn your CV all in the bid to make you the best Product Manager. PROBAR is a community of great product manager and its for everyone who wans to be a great Product Manager.',
 'Learning at PROBAR was one of the best decisions I made last year. The program was really an eye opener to what product management is all about. I am an engineer who was eager to explore and is still exploring the opportunities in tech. I am grateful for the work Probar did on me with the training and the platforms they provide me with. I have been able to work on two projects with my team that I got from the PROBAR community. Their dedication to growth is amazing. So,if you are looking to start or further your career in tech, PROBAR is the right place to learn',
  'Joining Probar product management beginner’s class was a great decision I made, I was a bit skeptical that I wouldn’t gain the basic knowledge I needed about Product Management but i was surprised at the amazing teaching process, and the amount of knowledge shared within the duration of the lectures. Probar has its unique ways of explaining till you understand plus mentorship opportunity even after you are done with the course and for this I am grateful/happy for the experience. I will highly recommend Probar product management beginner’s class to anyone who is interested in Product Management, the level of knowledge you would gain would Wow you. As long as you choose Probar you are set in the right direction.',
  'My learning experience with probar has been worthwhile, I\'m proud to be a certified product manager'
]

export const nameArray = [ 'Anuoluwapo Fanegan', 'Mariam Abdulganiyu', 'Amaka Onyejuiwa', 'Oluwatoyosi', 'Maryann Ndedigwe', 'Olumide Adelewa' ] 